### ISSUE TITLE
Consider posting full installation instructions

### ISSUE THREAD

**Issue by lemire** [gerrymanoim/libpy_simdjson#10]
To get this to install properly, I had to do...

```
PYTHON=python3 pip3 install libpy
PYTHON=python3 pip3 install libpy_simdjson
```

Under Linux, I had to do first...

```
apt-get install python3-dev
```

Note that `libpy` requires Python 3, which means that `libpy_simdjson` will require Python3.

**Comment by gerrymanoim** [comment]
Yep - fair point. I opened an issue under `libpy` to remind us to clarify this: https://github.com/quantopian/libpy/issues/194. 

I'll add a similar clarification here. 

Thanks for the feedback!

**Comment by lemire** [comment]
I am very impressed, by the way.

**Comment by gerrymanoim** [comment]
Thanks! We were very impressed by simdjson and thought it was a great fit for binding via `libpy`.
