### ISSUE TITLE
Instead of returning a KeyError at_pointer returns the value of the valid root

### ISSUE THREAD

**Issue by hglaude** [gerrymanoim/libpy_simdjson#28]
Hello,

Step to reproduce:
```
>>> import simdjson
>>> parser = simdjson.Parser()
>>> t = '{"foo": "bar"}'
>>> d = parser.parse(t)      
>>> d.at_pointer("/foo")
'bar'
>>> d.at_pointer("/bar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'No such key'
>>> d.at_pointer("/foo/foo")
'bar'
```
I expect that `d.at_pointer("/foo/foo")` returns a KeyError to be consistent with `d.at_pointer("/bar")`.

Best,
Hadrien

**Comment by gerrymanoim** [comment]
Hmm that's odd. The spec at https://tools.ietf.org/html/rfc6901 leaves it to the implementation to handle "A pointer that references a nonexistent value". 

Need to confirm how simdjson handles this in master (`libpy_simdjson` is on the most recent 5.0 release.).

**Comment by gerrymanoim** [comment]
Off master, `simdjson` throws an error. On 5.0 it exhibits the behavior you described. This will be fixed in `libpy_simdjson` when `simdjson` publishes a new version and we update it here.
